version: 2

models:
  - name: dim_listings_cleansed
    description: Cleansed table that contains Airbnb listings
    columns:
      - name: listing_id
        description: Primary key
        data_tests:
          - unique
          - not_null

      - name: host_id
        description: The hosts' id. References to the host table
        data_tests:
         - not_null
         - relationships:
              to: ref('dim_hosts_cleansed') 
              field: host_id
          
      - name: room_type
        description: Type of the appartment room/ type
        data_tests:
        - accepted_values:
            values: ['Entire home/apt', 'Private room', 'Shared room', 'Hotel room']

      - name: minimum_nights
        description: '{{doc("dim_listing_cleansed__minimum_nights")}}'
        data_tests:
        - positive_value

  - name: dim_hosts_cleansed
    columns:
      - name: host_id
        description: Host id
        data_tests:
          - unique
          - not_null

      - name: host_name
        description: Host name.
        data_tests:
          - not_null

      - name: is_superhost
        description: Is the person a good or bad host.
        data_tests:
        - accepted_values: 
            values: ['t', 'f']
